### PR TITLE
Multiple Git hosts support (Gitea, Bitbucket, AzureDevOps)

### PR DESCRIPTION
**Pull request by ycherkes**
Compiled package for testing: [OpenOnGitHub.zip](https://github.com/neuecc/Open-on-GitHub/files/11442560/OpenOnGitHub.zip)

Changes:

- update LibGit2Sharp to version 0.27.0.0 (arm64 support)
- update .NetFramework to version 4.7.2 - it's safe for Visual Studio 2017, see https://stackoverflow.com/questions/56616487/net-framework-version-compatibility-for-visual-studio-package https://learn.microsoft.com/en-us/visualstudio/releases/2017/vs2017-system-requirements-vs
- fix missing Visual Studio 2022 json file context menu https://github.com/neuecc/Open-on-GitHub/issues/14
- add support for Solution Explorer and Tab Bar https://github.com/neuecc/Open-on-GitHub/issues/16
- add functionality to work on other Version Control Tools (Gitea, Bitbucket, AzureDevOps) https://github.com/neuecc/Open-on-GitHub/issues/15
- add arm64 support
- add main branch support https://github.com/neuecc/Open-on-GitHub/issues/12
- rename menu "Open on GitHub -> master" to "Git Hub -> Open main"

**Useful repositories:**
* https://github.com/ziyasal/vscode-open-in-github
* https://github.com/veler/CopyGitLink

### CODE REVIEW

**Comment by neuecc** [comment]
thank you for great improvement!
I'll check soon!

**Comment by neuecc** [comment]
It looks good, but I can't confirm the details.
I will merge and release it for now!

**Comment by neuecc** [comment]
changing `<ButtonText>Git Hub</ButtonText>` is not good(GitHub is correct)
I'll just change it back there, `Open on GitHub`.

**Comment by neuecc** [comment]
pulished 2.0.1 package in vs gallery.

**Comment by ycherkes** [comment]
> I'll just change it back there, `Open on GitHub`.

I think if you reverted the text of parent menu to "Open on GitHub", then you should also remove word "Open" in submenus.
Thank you very much for your extension.

**Comment by maikebing** [comment]
Open on Web 
Use git url to determine GitHub or other  git host

**Comment by ycherkes** [comment]
There are two one more places where the "Open" word presents: https://github.com/neuecc/Open-on-GitHub/blob/master/OpenOnGitHub/GitRepository.cs#L83-L86

https://github.com/neuecc/Open-on-GitHub/blob/master/OpenOnGitHub/GitRepository.cs#L94-L97

**Pull request merged**
