### PR TITLE
Closes issue #18 - Support for enterprise gitHub

### PR DESCRIPTION
**Pull request by ycherkes**
1. Use GitHubLabUrlProvider as a fallback provider.
2. Fix the extension URL.

Compiled package for testing: 
[OpenOnGitHub.zip](https://github.com/neuecc/Open-on-GitHub/files/13256180/OpenOnGitHub.zip)

### CODE REVIEW

**Comment by neuecc** [comment]
thanks! I'll release soon.

**Comment by ycherkes** [comment]
@neuecc Have you verified if it works? If not, I would ask you to wait until @ridilculous or @twastvedt confirm that.

**Comment by neuecc** [comment]
oh, not yet......

**Comment by twastvedt** [comment]
Building and running the update works for me with our corporate GitHub! Thanks!

**Pull request merged**
