### PR TITLE
feat: vs2019 support

### PR DESCRIPTION
**Pull request by guitarrapc**
* added vs2019 support
* clean up .gitignore for latest visualstudio support. (`gibo dump visualstudio`)

### CODE REVIEW

**Comment by guitarrapc** [comment]
I've found even this update enable you to install on vs2019, still warn for Deprecated API.

image

**Comment by guitarrapc** [comment]
deprecated api is caused by `: Package`, another pr is on https://github.com/neuecc/Open-on-GitHub/pull/9.

**Comment by neuecc** [comment]
thanks, curretnly I'm not installed VS2019 RC yet but check soon.

**Comment by neuecc** [comment]
VS2019 was released, I'll release soon.

**Pull request merged**
